services:
  service1:
    build: ./service1
    container_name: service1
    ports:
      - "8199:8199"
    restart: always
    networks:
      - services
    volumes:
      - ./vStorage:/data
      
  service2:
    build: ./service2
    container_name: service2
    restart: always
    networks:
      - services
    volumes:
      - ./vStorage:/data

  storage:
    build: ./storage
    container_name: storage
    restart: always
    networks:
      - services
    volumes:
      - storage:/storage

networks:
  services:

volumes:
  storage: